name: Minify Javascript File
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Make dist directory
        run: mkdir dist

      - name: Minify
        run: npm run minify

      - name: Copy source
        run: cp src/* dist

#      - name: Publish NPM package
#        run: npm publish
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}